version: '3.3'
services:
  postgres:
    container_name: pgsql_PRO
    image: postgres:11
    restart: always
    environment:
    - POSTGRES_DB=BD_Budget
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456789
    - PGDATA=/data
    ports:
      - 5432:5432
    volumes:
      - ./bdd:/var/lib/postgresql/data
  web:
    restart: always
    depends_on:
    - postgres
    build: .
    ports:
    - 80:9000
    volumes:
    - ~/.ivy2:/root/.ivy2
    - ~/.sbt:/root/.sbt
    links:
    - postgres
    environment:
      - POSTGRES_SERVICE_HOST=postgres

  volumes:
    ./bdd:
      driver: test